### ISSUE TITLE
FormatException: Unterminated string

### ISSUE THREAD

**Issue by LeiTi34** [joaquimguimaraes/chiabot#16]
Since today, the bot crashes with the following exception:

```Unhandled exception:
FormatException: Unterminated string (at character 745473)
...ime":0.03557,"totalPlots":557,"proofs":0},{"timestamp":1621835827601,"eligi
                                                                              ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:515)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41)
#3      JsonDecoder.convert (dart:convert/json.dart:506)
#4      JsonCodec.decode (dart:convert/json.dart:157)
#5      jsonDecode (dart:convert/json.dart:96)
#6      Cache.load (package:chiabot/cache.dart:80)
#7      Cache.init (package:chiabot/cache.dart:54)
#8      main (file:///home/runner/work/chiabot/chiabot/chiabot.dart:60)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by LeiTi34** [comment]
I think the easiest way to fix this for me and get the bot running again, would be clearing the log file, with the wrong character. But I'm not sure, at which file I should look.

**Comment by joaquimguimaraes** [comment]
Hey, seems like your .chiabot_cache.json file is corrupt. Please delete it and launch chiabot again.

**Comment by LeiTi34** [comment]
Thank you, now everything works again :)
